# Generated by Django 3.2.3 on 2021-05-21 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Physiotherapist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pp_physiotherapist_master',
            name='degree',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='pp_physiotherapist_master',
            name='pp_pm_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pp_physiotherapist_master',
            name='regd_no_1',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='pp_physiotherapist_master',
            name='regd_no_2',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
