# Generated by Django 3.2.3 on 2021-05-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Physiotherapist', '0003_alter_pp_physiotherapist_master_regd_no_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pp_physiotherapist_master',
            name='regd_no_2',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),
    ]
