# Generated by Django 3.2.3 on 2021-05-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Physiotherapist', '0004_alter_pp_physiotherapist_master_regd_no_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='pp_physiotherapist_master',
            name='facebook',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pp_physiotherapist_master',
            name='linkedin',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pp_physiotherapist_master',
            name='landline',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='pp_physiotherapist_master',
            name='whatsapp_no',
            field=models.CharField(max_length=12),
        ),
    ]
